[pytest]
testpaths = src/step_definitions
python_files = test_*.py
python_functions = test_*
pythonpath = src

addopts =
    -v
    --html=reports/test_report.html
    --self-contained-html
    --junitxml=reports/junit_results.xml

generate_report_on_test = True

markers =
    api: API automation tests
    smoke: Critical smoke tests
    positive: Positive API scenarios
    negative: Negative API scenarios
    ui: Playwright UI tests