[pytest]
testpaths = src/step_definitions
python_files = test_*.py
python_functions = test_*
pythonpath = src

addopts =
    -v
    --html=reports/test_report.html
    --self-contained-html

generate_report_on_test = True